import Head from 'next/head'
import Navbar from "@/components/Navbar";
import Addword from "@/components/settings/Addword";

export default function Settings() {
  return (
     <>
       <Head>
         <title>Jeux du pendu</title>
         <meta name="description" content="Generated by create next app" />
         <meta name="viewport" content="width=device-width, initial-scale=1" />
         <link rel="icon" href="/favicon.ico" />
       </Head>
       <Navbar/>
       <main>
         <Addword/>
         <p>params</p>
       </main>
     </>
  )
}
